cat > buildspec.yml << 'EOF'
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running tests...
      - npm test
      - echo Building the application...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing the artifacts...

artifacts:
  files:
    - app.js
    - package.json
    - package-lock.json
    - appspec.yml
    - scripts/**/*
    - node_modules/**/*
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
EOF
