cat > appspec.yml << 'EOF'
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root
EOF
